version: "3.11"
services:
  service-1:
    container_name: cinema-app
    image: pamswi/cinema-app:v1
    environment:
      DATABASE_URI: ${DATABASE_URI}
    build: ./
    deploy:
      replicas: 4
    networks:
      - my-network


  service-2:
    container_name: cinema
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: cinema-data
        target: /var/lib/mysql
    networks:
      - my-network

  proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - "service-1"
    networks:
      - my-network

volumes:
  cinema-data:

networks:
  my-network:
